### ISSUE TITLE
Replace `get_post_meta()` uses where we are fetching order meta data

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-subscriptions-core#141]
Product thread: pdjTHR-Xp-p2

---

## Description

With Custom Order Tables being worked on by the WC Core team ([public announcement](https://developer.woocommerce.com/2022/01/17/the-plan-for-the-woocommerce-custom-order-table/)), we need to begin to think about updating the Subscriptions Core library to remove any code that is calling WP Post API functions.

In this issue we're tackling only the uses of `get_post_meta()` where an order ID is passed. Subscription ID or Product ID are fine at this stage.

### How to update code?

These uses should be replaced with `$object->get_meta( $property )` or `$object->get_{property_name}()` if the function exists.

### What code needs replacing?

Code that needs to be updated:
- [x] `WC_Subscriptions_Order::get_meta()`
- [x] `WCS_Post_Meta_Cache_Manager::maybe_update_for_post_change()`
  - When `$post_id` belongs to a `shop_order`
- [x] `wcs_get_objects_property()`
  - Can use https://github.com/woocommerce/woocommerce-subscriptions/pull/3814/files for inspiration

### Code to ignore 
- `WCS_Related_Order_Store_CPT::get_related_subscription_ids()`
- `WCS_Related_Order_Store_CPT::add_relation()`
- `test-class-wcs-related-order-store-cpt.php`
- `test-class-wcs-related-order-store-cached-cpt.php`
- `WCS_PayPal_Standard_IPN_Handler::get_order_id_and_key()`
  - This can probably be ignored for now because 'shop_order' post type is never queried (even though it's the default option when calling the function). I believe this default option was pre-WC subscriptions 2.0 before a subscription post type existed and we had to use the parent order ID.
- `WCS_Post_Meta_Cache_Manager_Many_To_One::meta_updated()`
  - This class is only used for `'shop_subscription'` post types
- `WC_Subscriptions_Synchroniser::order_contains_synced_subscription()`
  - This function can be removed as part of removing functions deprecated in 2.0

These will be tackled in a separate issue with a refactor of the WCS_Related_Order_Store_CPT class. See internal discussion here: pdjTHR-Y8-p2

- `WCS_Upgrade_1_2::init()`
- `class WCS_Upgrade_2_0`

Upgrade scrips can be ignored at this stage as these might be removed from the next version. See internal discussion here: pdjTHR-Y8-p2
 

## Product impact

- [x] Does this feature affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [x] Does this feature affect WooCommerce Payments? yes/no/tbc, add issue ref
