### ISSUE TITLE
EPIC: Use CRUD APIs when interacting with Order objects

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-subscriptions-core#152]
## Description

Custom Order Tables are coming to WooCommerce sometime this year and with that, any code we have that is fetching order data from posts or postmeta will no longer work as intended.

This epic is to keep track of the progress with updating our Subscriptions Core library to remove usages of the following functions when trying to fetch/update orders:
 - `get_post_meta()` - issue opened
 - `update_post_meta()` - issue opened
 - `get_posts()` - issue opened
 - `add_post_meta()` - no affected code found
 - `get_post_type()` - issue opened
 - `get_post_type_object()` - no affected code found

## Issues

- [x] https://github.com/Automattic/woocommerce-subscriptions-core/issues/144
- [x] https://github.com/Automattic/woocommerce-subscriptions-core/issues/142
- [x] https://github.com/Automattic/woocommerce-subscriptions-core/issues/141
- [x] https://github.com/Automattic/woocommerce-subscriptions-core/issues/153

## Additional context

This issue is part of internal project thread: pdjTHR-Xp-p2

**Comment by brucealdridge** [comment]
marking as closed as all sub-tasks are now complete.
