### ISSUE TITLE
[EPIC] Introduce Expiration and Renewal Notifications

### ISSUE THREAD

**Issue by xristos3490** [Automattic/woocommerce-subscriptions-core#645]
### Description

This epic is created to track the implementation of expiration and renewal notifications feature.

PRD: pfwcF5-Gn-p2
Project P2: pfwcF5-JS-p2

### Task List

- Create a scheduler class based on the `WCS_Scheduler` interface to manage hooks triggered by subscription changes.
- Develop a singleton controller to manage emails and create all necessary HTML and plain email templates.
- Copy the core `Automattic\WooCommerce\Internal\BatchProcessing\BatchProcessingController` into the plugin.
- Create a batch processor class using the batch processing interface to manage changes to the offset option (days prior to an event).
- Develop another batch processor based on the same interface to support a new debug tool found under WooCommerce > Status > Tools, which will fix all AS actions if necessary.
- Implement tracking data to monitor the usage of the new option.
- Create a dismissible admin notice to inform existing stores about the new feature.
- Ensure that everything is protected by unit tests.

#### Main Pull Request
- [x] https://github.com/Automattic/woocommerce-subscriptions-core/pull/648 (Main PR)

#### Improvements
- [x] https://github.com/Automattic/woocommerce-subscriptions-core/pull/706
- [x] https://github.com/Automattic/woocommerce-subscriptions-core/pull/694
- [x] https://github.com/Automattic/woocommerce-subscriptions-core/pull/703
- [x] https://github.com/Automattic/woocommerce-subscriptions-core/pull/677
- [x] https://github.com/Automattic/woocommerce-subscriptions-core/pull/708
- [x] https://github.com/Automattic/woocommerce-subscriptions-core/pull/713

#### Batch Processing
- [x] https://github.com/Automattic/woocommerce-subscriptions-core/pull/654
- [x] https://github.com/Automattic/woocommerce-subscriptions-core/pull/673
- [x] https://github.com/Automattic/woocommerce-subscriptions-core/pull/689
- [x] https://github.com/Automattic/woocommerce-subscriptions-core/pull/696
- [x] https://github.com/Automattic/woocommerce-subscriptions-core/pull/704

#### Testing
- [x] https://github.com/Automattic/woocommerce-subscriptions-core/pull/684

#### Tracking
- [x] https://github.com/Automattic/woocommerce-subscriptions-core/pull/695
